language: python
python:
  - 2.7
  - 3.4
before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
